queue:
  name: Hosted VS2017
  condition: succeeded()
  demands: msbuild

variables:
  "Parameters.solution": MSBuildLocator.sln
  BuildConfiguration: Release
  SignType: Test
  BuildPlatform: ''

steps:
- task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@1
  displayName: Install Signing Plugin
  inputs:
    signType: '$(SignType)'
  enabled: false

- task: MSBuild@1
  displayName: /t:Pack
  inputs:
    solution: MSBuildLocator.sln
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/t:Pack /restore'

- task: CopyFiles@2
  displayName: Collect Symbols
  inputs:
    SourceFolder: 'src/MSBuildLocator'
    Contents: '**\*.pdb'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/symbols'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: Upload Symbols Artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/symbols'
    ArtifactName: Symbols

- task: CopyPublishBuildArtifacts@1
  displayName: Upload Bin to drop
  inputs:
    Contents: |
     src\MSBuildLocator\bin\**
    ArtifactName: bin
    ArtifactType: Container

- task: CopyPublishBuildArtifacts@1
  displayName: Upload NuGet to drop
  inputs:
    Contents: |
     src\MSBuildLocator\bin\$(BuildConfiguration)\*.nupkg
    ArtifactName: pkg
    ArtifactType: Container

- task: CopyPublishBuildArtifacts@1
  displayName: Upload MicroBuildOutputs to drop
  inputs:
    CopyRoot: '$(Build.StagingDirectory)\MicroBuild\Output'
    Contents: '**'
    ArtifactName: MicroBuildOutputs
    ArtifactType: Container
  continueOnError: true

- task: CopyPublishBuildArtifacts@1
  displayName: Upload logs to drop
  inputs:
    Contents: '**\*.log'
    ArtifactName: logs
    ArtifactType: Container
  condition: succeededOrFailed()

- task: ms-vseng.MicroBuildTasks.521a94ea-9e68-468a-8167-6dcf361ea776.MicroBuildCleanup@1
  displayName: Execute cleanup tasks
  enabled: false

