queue:
  name: Hosted VS2017
  demands: msbuild

variables:
  "Parameters.solution": MSBuildLocator.sln
  BuildConfiguration: Release
  SignType: Test
  BuildPlatform: ''

steps:
- task: MSBuild@1
  displayName: /t:Pack
  inputs:
    solution: MSBuildLocator.sln
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/t:Pack /restore'

- task: CopyFiles@2
  displayName: Collect Symbols
  inputs:
    SourceFolder: 'src/MSBuildLocator'
    Contents: '**\*.pdb'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/symbols'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: Collect Packages
  inputs:
    SourceFolder: 'src/MSBuildLocator'
    Contents: '**\*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/pkg'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: Collect logs
  inputs:
    SourceFolder: 'src/MSBuildLocator'
    Contents: '**\*.log'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/logs'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: Upload Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: drop
    ArtifactType: Container
